Repository adaptlearning/adapt_authoring, pull requests merged in 2019-01, with the labels that each got.

#2154 use snackbar extension instead of alert
  frontend/src/modules/editor/global/views/editorView.js
  frontend/src/modules/projects/views/projectView.js
Labels: C: Front-end, S: awaiting-review

#2152 add ability to clone list items
  frontend/src/modules/scaffold/less/forms.less
  frontend/src/modules/scaffold/templates/listItem.hbs
  frontend/src/modules/scaffold/views/scaffoldListView.js
Labels: S: awaiting-review

#2129 build app as part of CI
  .travis.yml
Labels: S: awaiting-review

#2166 expose installed versions
  routes/index/index.hbs
  routes/index/index.js
Labels: S: awaiting-review, T: enhancement

#2158 remove backbone-forms child views
  frontend/src/modules/scaffold/views/scaffoldItemsModalView.js
Labels: S: awaiting-review

#2193 Admins shouldn't be able to change user passwords if smtp is enabled.
  frontend/src/modules/userManagement/templates/user.hbs
  lib/usermanager.js
Labels: S: awaiting-review

#2153 Snackbar Notify extension
  frontend/src/modules/editor/global/views/editorView.js
  frontend/src/modules/notify/index.js
  frontend/src/modules/notify/plugins/snackbar/index.js
  frontend/src/modules/notify/plugins/snackbar/less/snackbar.less
  frontend/src/modules/projects/views/projectView.js
Labels: C: Front-end, S: awaiting-review

#2194 Admins should be able to give new users a name
  frontend/src/modules/userManagement/templates/addUser.hbs
  frontend/src/modules/userManagement/views/addUserView.js
Labels: S: awaiting-review

#2197 Admins should be able to send users a welcome email
  frontend/src/modules/userManagement/templates/user.hbs
  frontend/src/modules/userManagement/views/userView.js
  lib/templates/emails/invite.hbs
  lib/templates/emails/passwordReset.hbs
  lib/templates/emails/style.css
  lib/usermanager.js
  plugins/auth/local/index.js
  routes/lang/en-application.json
Labels: S: awaiting-review

#2206 underscore 1.9.1
  frontend/src/libraries/underscore.js
Labels: S: awaiting-review

#2195 Admins should be warned that the reset password button will send an email
  frontend/src/modules/userManagement/views/userView.js
  routes/lang/en-application.json
Labels: S: awaiting-review
