Repository adaptlearning/adapt_authoring, pull requests merged in 2019-02, with the labels that each got.

#2201 Only remove one matching course asset record
  frontend/src/modules/scaffold/views/scaffoldAssetView.js
Labels: S: awaiting-review

#2210 remove mejs
  frontend/src/core/app.js
  frontend/src/core/config.js
  frontend/src/libraries/mediaelement-and-player.js
  frontend/src/modules/assetManagement/assets/background.png
  frontend/src/modules/assetManagement/assets/bigplay.png
  frontend/src/modules/assetManagement/assets/bigplay.svg
  frontend/src/modules/assetManagement/assets/controls-ted.png
  frontend/src/modules/assetManagement/assets/controls-wmp-bg.png
  frontend/src/modules/assetManagement/assets/controls-wmp.png
  frontend/src/modules/assetManagement/assets/controls.png
  frontend/src/modules/assetManagement/assets/controls.svg
  frontend/src/modules/assetManagement/assets/flashmediaelement.swf
  frontend/src/modules/assetManagement/assets/loading.gif
  frontend/src/modules/assetManagement/assets/silverlightmediaelement.xap
  frontend/src/modules/assetManagement/less/mej.less
  frontend/src/modules/assetManagement/templates/assetManagementPreview.hbs
  frontend/src/modules/assetManagement/views/assetManagementPreviewView.js
Labels: S: awaiting-review

#2171 use npm to install ffmpeg and ffprob
  install.js
  lib/configuration.js
  lib/installHelpers.js
  package.json
  plugins/filestorage/localfs/index.js
Labels: S: awaiting-review, T: enhancement

#2122 User management filter / search
  frontend/src/libraries/pikaday/css/pikaday.less
  frontend/src/modules/sidebar/less/sidebar.less
  frontend/src/modules/userManagement/collections/userCollection.js
  frontend/src/modules/userManagement/index.js
  frontend/src/modules/userManagement/less/userManagement.less
  frontend/src/modules/userManagement/models/userModel.js
  frontend/src/modules/userManagement/templates/user.hbs
  frontend/src/modules/userManagement/templates/userManagement.hbs
  frontend/src/modules/userManagement/templates/userManagementFilter.hbs
  frontend/src/modules/userManagement/templates/userManagementSidebar.hbs
  frontend/src/modules/userManagement/views/filterView.js
  frontend/src/modules/userManagement/views/userManagementSidebarView.js
  frontend/src/modules/userManagement/views/userManagementView.js
  frontend/src/modules/userManagement/views/userView.js
  routes/lang/en-application.json
Labels: S: awaiting-review

#2215 fix paste zone button styling
  frontend/src/modules/editor/contentObject/less/editorPage.less
  frontend/src/modules/editor/global/less/editor.less
Labels: S: awaiting-review

#2128 Course force rebuild
  frontend/src/modules/editor/global/templates/partials/part_editorCommon.hbs
  frontend/src/modules/editor/global/views/editorView.js
  frontend/src/modules/sidebar/less/sidebar.less
  frontend/src/modules/sidebar/views/sidebarItemView.js
  plugins/output/adapt/publish.js
  routes/lang/en-application.json
Labels: S: awaiting-review

#2185 Get schema from framework clone
  frontend/src/modules/scaffold/views/scaffoldListView.js
  lib/contentmanager.js
  lib/installHelpers.js
  test/entry.js
Labels: S: awaiting-review

#2160 handle unshared courses on user delete
  frontend/src/modules/userManagement/less/userManagement.less
  frontend/src/modules/userManagement/templates/user.hbs
  frontend/src/modules/userManagement/views/userView.js
  lib/helpers.js
  lib/usermanager.js
  routes/lang/en-application.json
Labels: S: awaiting-review

#2156 drag and drop hotgraphic pin editor
  frontend/src/modules/scaffold/index.js
  frontend/src/modules/scaffold/less/scaffoldAssetItem.less
  frontend/src/modules/scaffold/templates/scaffoldAssetItem.hbs
  frontend/src/modules/scaffold/views/scaffoldAssetItemView.js
  frontend/src/modules/scaffold/views/scaffoldListView.js
Labels: S: awaiting-review, T: question

#2232 Call next on error
  lib/helpers.js
Labels: S: awaiting-review, T: bug

#2208 Change your own email via the profile view
  frontend/src/modules/user/models/userProfileModel.js
  frontend/src/modules/user/templates/userProfile.hbs
  frontend/src/modules/user/views/userProfileView.js
  lib/usermanager.js
Labels: S: awaiting-review
